version: "3.9"
networks:
  default:
    name: redis-net
    external: true
services:
  redis01:
    image: redis:7.0.5
    ports:
      - "6379:6379"
    command: redis-server --cluster-enabled yes --port 6379
  redis02:
    image: redis:7.0.5
    ports:
      - "6380:6380"
    command: redis-server --cluster-enabled yes --port 6380
  redis03:
    image: redis:7.0.5
    ports:
      - "6381:6381"
    command: redis-server --cluster-enabled yes --port 6381
